import type { Metadata } from 'next';
// Next.js đã tích hợp font của google vào bên trong dự án
import { Inter } from 'next/font/google'; // Re-setup font
import './globals.css';

// Setup lại font chữ cho dự án
const inter = Inter({ subsets: ['vietnamese'] });
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// Root layout
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                // Re-setup font chữ
                className={inter.className}
            >
                {children}
            </body>
        </html>
    );
}
