import type { Metadata } from 'next';
// Next.js đã tích hợp font của google vào bên trong dự án
import { Inter } from 'next/font/google'; // Re-setup font
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';

// Setup lại font chữ cho dự án
const inter = Inter({ subsets: ['vietnamese'] });
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// Root layout: Đây là layout gốc của toàn bộ ứng dụng
// Mọi thứ bên trong layout này sẽ được render trên tất cả các trang con
// Vì vậy, bạn có thể đặt các thành phần như header, footer, sidebar ở đây
// Ngoài ra, bạn cũng có thể thêm các thẻ meta, link css, js ở đây
// Lưu ý: Không nên đặt các thành phần có trạng thái (state) ở đây vì nó sẽ làm mất trạng thái khi chuyển trang
// Nếu cần thiết, hãy sử dụng Context hoặc Redux để quản lý trạng thái toàn cục
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    // Re-setup font chữ
                    className={inter.className}
                >
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
